const CONFIG = {
  MMO_ECC_ORCHESTRATION_SVC_URL: process.env.MMO_ECC_ORCHESTRATION_SVC_URL,
  MMO_ECC_REFERENCE_SVC_URL: process.env.MMO_ECC_REFERENCE_SVC_URL,
  LIMIT_ADD_SPECIES: process.env.LIMIT_ADD_SPECIES
};

export default CONFIG;